# Enable Continuous Integration with Travis-CI and Netlify
# https://arm.rbind.io/days/day1/bookdown/
language: R
sudo: false
cache:
  packages: true

script: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

deploy:
  provider: pages
  local_dir: _book
  skip_cleanup: true
  keep-history: true
  target_branch: gh-pages