# Enable Continuous Integration with Travis-CI and Netlify
# https://arm.rbind.io/days/day1/bookdown/
# OS ---------------------------------------------------------------------------
os: linux
dist: bionic

# meta -------------------------------------------------------------------------
language: R
r: 3.6.2
sudo: false
cache:
  packages: true
  
# stages -----------------------------------------------------------------------
stages:
  - name: deploy
    if: branch = master | branch = develop

# jobs -------------------------------------------------------------------------
jobs:
  include:
    - stage: "deploy"
      name: "bookdown"
      script: Rscript -e 'bookdown::render_book("index.Rmd", "bookdown::gitbook")'

# job lifecycle ----------------------------------------------------------------
install:
  - R -q -e 'if (!requireNamespace("remotes")) install.packages("remotes")'
  - R -q -e 'if (!requireNamespace("desc")) install.packages("desc")'
  - R -q -e 'try(options(repos = paste0("https://mran.microsoft.com/snapshot/", desc::description$new()$get_field("Date"))))'
  - R -q -e 'remotes::install_deps(dependencies = TRUE)'
deploy:
  - provider: pages
    local_dir: _book
    skip_cleanup: true
    keep-history: true
    github_token: $GITHUB_PAT
    target_branch: gh-pages
    on:
      branch: master
  - provider: pages
    local_dir: _book
    skip_cleanup: true
    keep-history: false
    github_token: $GITHUB_PAT
    target_branch: proofreading
    on:
      branch: develop
   