# Enable Continuous Integration with Travis-CI and Netlify
# https://arm.rbind.io/days/day1/bookdown/
# OS ---------------------------------------------------------------------------
os: linux
dist: bionic

# meta -------------------------------------------------------------------------
language: R
r: 3.6.2
sudo: false
cache:
  packages: true
  
# stages -----------------------------------------------------------------------
stages:
  - name: deploy
    if: branch = master | branch = develop

# jobs -------------------------------------------------------------------------
jobs:
  include:
    - stage: "deploy"
      name: "bookdown"
      script: 
      - Rscript -e 'local({setwd("./manuscript"); bookdown::render_book("index.Rmd", "bookdown::gitbook")})'
      - Rscript -e 'fs::dir_copy("./manuscript/_book", ".")'

# job lifecycle ----------------------------------------------------------------
install:
  - R -q -e 'if (!require(remotes, quietly = TRUE)) utils::install.packages("remotes")'  
  - R -q -e 'remotes::install_cran(c("desc", "fs"), quiet = TRUE)' 
  - R -q -e 'try(options(repos = paste0("https://mran.microsoft.com/snapshot/", desc::description$new()$get_field("Date")))); remotes::install_deps(dependencies = TRUE)'
deploy:
  - provider: pages
    local_dir: _book
    skip_cleanup: true
    keep-history: true
    github_token: $GITHUB_PAT
    target_branch: gh-pages
    on:
      branch: master
  - provider: pages
    local_dir: _book
    skip_cleanup: true
    keep-history: false
    github_token: $GITHUB_PAT
    target_branch: proofreading
    on:
      branch: develop
   