```{r include=FALSE, cache=FALSE}
DESCRIPTION <- desc::description$new("../DESCRIPTION")

makesvg <- function(name = "svg", width = 300, height = 200) {
    if (name == "svg") {
        selector <- "svg"
    } else {
        selector <- paste0("svg#", name)
    }
    
    cat(paste0("<svg id='", name, "' width='", width,"' height='", height, "'>\n"))
    cat(paste0("<rect x='0' y='0' width='", width, "' height ='",  height, "' fill = 'lightblue'></rect>\n"))
    cat(paste0("<text x='10' y='", height - 10, "' style = 'font-size: 80%;'>", selector, "</text>\n"))
    cat("</svg>")
}

knitr::opts_chunk$set(
    out.width='100%',
    echo = FALSE,
    message = FALSE,
    warning = FALSE,
    comment = "## R output ## ",
    # comment = "#>",
    fig.retina = 0.8, # figures are either vectors or 300 dpi diagrams
    dpi = 300,
    out.width = "70%",
    fig.align = 'center',
    fig.width = 6,
    fig.asp = 0.618,  # 1 / phi
    fig.show = "hold",
    eval.after = 'fig.cap' # so captions can use link to demos
)
```
# Preface {-}

<!-- see https://github.com/hadley/mastering-shiny/blob/master/introduction.Rmd -->

## Colophon

This book was written in [RStudio](http://www.rstudio.com/ide/) using
[bookdown](http://bookdown.org/). The [website](http://mastering-shiny.org/) is
hosted with [netlify](http://netlify.com/), and automatically updated after
every commit by [travis-ci](https://travis-ci.org/). The complete source is
available from [GitHub](https://github.com/Kiwi-Random-House/template.book).

This version of the book was built with `r R.version.string` and the following
packages:

```{r, echo = FALSE, results="asis"}
imports <- subset(DESCRIPTION$get_deps(), type == "Imports", "package", TRUE)
pkgs <- sessioninfo::package_info(sort(imports), dependencies = FALSE)
df <- tibble::tibble(
  package = pkgs$package,
  version = pkgs$ondiskversion,
  source = gsub("@", "\\\\@", pkgs$source)
)
knitr::kable(df, format = "markdown")
```

```{r, echo = FALSE}
ruler <- function(width = getOption("width")) {
  x <- seq_len(width)
  y <- dplyr::case_when(
    x %% 10 == 0 ~ as.character((x %/% 10) %% 10),
    x %% 5 == 0  ~ "+",
    TRUE         ~ "-"
  )
  cat(y, "\n", sep = "")
  cat(x %% 10, "\n", sep = "")
}
```

```{r, include = FALSE}
ruler()
```
